#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Loads extra odoo.conf from environment variable

:env EXTRA_ODOO_CONF:
"""

import os
import logging

_logger = logging.getLogger(__name__)


RESOURCES = os.environ.get("RESOURCES")
EXTRA_ODOO_CONF = os.environ.get("ODOO_CONF")
EXTRA_ODOO_CONF_FILENAME = "999-entrypoint.conf"

# Deprecated
if not EXTRA_ODOO_CONF:
    EXTRA_ODOO_CONF = os.environ.get("EXTRA_ODOO_CONF")
    if EXTRA_ODOO_CONF:
        _logger.warning(
            "IMPORTANT: EXTRA_ODOO_CONF has been deprecated. Use ODOO_CONF instead."
        )


if EXTRA_ODOO_CONF:
    _logger.info("Loading extra odoo.conf:\n\n%s" % EXTRA_ODOO_CONF)
    config_file = os.path.join(RESOURCES, "conf.d", EXTRA_ODOO_CONF_FILENAME)
    with open(config_file, "w+") as file:
        file.write(EXTRA_ODOO_CONF)
