#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import subprocess
import logging
_logger = logging.getLogger(__name__)

SOURCES = os.environ.get("SOURCES")
ODOO_VERSION = os.environ.get("ODOO_VERSION")
ODOO_SOURCE_PATH = os.path.join(SOURCES, "odoo")
ODOO_EGGINFO_PATH = os.path.join(ODOO_SOURCE_PATH, "odoo.egg-info")

if os.path.isdir(ODOO_SOURCE_PATH):
    # The build runs 'pip install -e' on the odoo src, which creates an
    # odoo.egg-info directory inside src/odoo. So when we run a container
    # with a volume shared with the host, we don't have this .egg-info
    # (at least the first time).
    # When it happens, we reinstall the odoo python package. We don't want to run
    # the install everytime because it would slow the start of the containers
    pip_list = subprocess.check_output(
        ["pip", "list", "--format=columns"],
        universal_newlines=True,
    )
    if not "/home/odoo/src/odoo" in pip_list:
        _logger.info("Installing odoo package..")
        subprocess.check_call([
            "pip", "install", "--no-cache-dir", "--no-deps", "--editable", ODOO_SOURCE_PATH
        ])
    # Make versions 7.0 to 9.0 have an `odoo` executable
    if not os.path.exists("/usr/local/bin/odoo"):
        _logger.info("Creating odoo symlink..")
        if ODOO_VERSION == "7.0":
            os.symlink("/usr/local/bin/openerp-server", "/usr/local/bin/odoo")
        elif ODOO_VERSION in ["8.0", "9.0"]:
            os.symlink("/usr/local/bin/odoo.py", "/usr/local/bin/odoo")
