#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import logging
_logger = logging.getLogger(__name__)


SOURCES = os.environ.get('SOURCES')
REPOSITORIES = os.path.join(SOURCES, 'repositories')
RESOURCES = os.environ.get('RESOURCES')

addons = [
    os.path.join(SOURCES, 'odoo', 'addons'),
]

# Handle versions <= 9.0, where odoo is called openerp
if os.environ.get('ODOO_VERSION') in ['6.0', '7.0', '8.0', '9.0']:
    addons.append(os.path.join(SOURCES, 'odoo', 'openerp', 'addons'))
else:
    addons.append(os.path.join(SOURCES, 'odoo', 'odoo', 'addons'))

# Add repositories
addons += [
    os.path.join(REPOSITORIES, d)
    for d in sorted(os.listdir(REPOSITORIES))
    if os.path.isdir(os.path.join(REPOSITORIES, d))
]

# Overwrite 10-addons.conf
_logger.debug('Updating addons_path.. %s' % addons)
with open(os.path.join(RESOURCES, 'conf.d', '10-addons.conf'), 'w+') as file:
    file.write('[options]\naddons_path = %s' % ','.join(addons))
