#!/usr/bin/env python

import os
from contextlib import closing
from configparser import RawConfigParser
from io import StringIO
from string import Template

import logging
_logger = logging.getLogger(__name__)


ODOO_VERSION = os.environ.get("ODOO_VERSION")
TARGET_FILE = os.environ.get("ODOO_RC")
CONFIG_DIR = os.path.join(os.environ.get("RESOURCES"), "conf.d")
CONFIG_FILES = []

# Default configuration values (when missing)
DEFAULTS = {
    "UNACCENT": "true",
    "PROXY_MODE": "true",
    "WITHOUT_DEMO": "all",
    "ADMIN_PASSWORD": "admin",
}

ENVIRON_WITH_DEFAULTS = dict(DEFAULTS, **os.environ)


# Read all configuration files found in those folders
_logger.info("Merging found configuration files in %s", TARGET_FILE)
parser = RawConfigParser(strict=False)
for file in sorted(os.listdir(CONFIG_DIR)):
    parser.read(os.path.join(CONFIG_DIR, file))


# Write it to a memory string object
with closing(StringIO()) as resultfp:
    parser.write(resultfp)
    resultfp.seek(0)
    # Process line by line
    result = []
    for line in resultfp:
        line = line.strip()
        # Try to expand variables, skip line if missing
        try:
            line = Template(line).substitute(ENVIRON_WITH_DEFAULTS)
        except KeyError as e:
            continue
        result.append(line)
    # Write it to destination
    with open(TARGET_FILE, "w+") as targetfp:
        targetfp.write('\n'.join(result))
