#!/bin/bash
set -e

# Default value (set to 0 to disable)
PGTIMEOUT=${PGTIMEOUT:-10}

if [ ${PGTIMEOUT:-10} -le 0 ]; then
    exit 0
fi

if [ -z "$PGHOST" ]; then
    echo "ERROR: PGHOST is not defined" 1>&2
    exit 1
fi

echo -n "Waiting for PostgreSQL to be ready ..."
start_time=$(date +%s)
until pg_isready -t 1 >/dev/null; do
    current_time=$(date +%s)
    elapsed_time=$((current_time - start_time))
    if [ "$elapsed_time" -ge "$PGTIMEOUT" ]; then
        echo "."
        echo "Unable to reach PostgreSQL server" 1>&2
        exit 1
    fi
    echo -n "."
done

echo " [OK]"
