#!/bin/bash
set -e

if [ ${WAIT_PG:-true} == "true" ]; then
    if [ -z "$PGHOST" ]; then
        echo "ERROR: PGHOST is not defined" 1>&2
        exit 1
    fi
    if [ -z "$PGUSER" ]; then
        echo "ERROR: PGUSER is not defined" 1>&2
        exit 1
    fi
    echo "Waiting for postgres to be ready..."
    pg_isready
fi
