#!/usr/bin/env python

import os
from subprocess import check_output

import logging
_logger = logging.getLogger(__name__)


def get_env_bool(key):
    return str(os.environ.get(key)).lower() in ["true", "1"]


UNACCENT = get_env_bool("UNACCENT")
PGDATABASE = os.environ.get("PGDATABASE")

# Install unaccent
if UNACCENT and PGDATABASE:
    try:
        res = check_output(["psql", "-c", "CREATE EXTENSION IF NOT EXISTS unaccent;"])
        _logger.info(res)
    except Exception as e:
        pass
