#!/bin/bash
set -ex

for target in base odoo odoo-e; do

    if [ "$target" == "odoo-e" ] && [ -z "$GITHUB_USER" ]; then
        echo "Can't build odoo-e without GITHUB_USER and GITHUB_TOKEN"
        continue
    fi

    docker image build \
        --file "$DOCKER_TAG.Dockerfile" \
        --build-arg VCS_REF="$GIT_SHA1" \
        --build-arg BUILD_DATE="$(date --rfc-3339 ns)" \
        --build-arg GITHUB_USER="$GITHUB_USER" \
        --build-arg GITHUB_TOKEN="$GITHUB_TOKEN" \
        --tag "$DOCKER_REPO:$DOCKER_TAG.$target" \
        --target $target \
        .

    if [ "$target" == "odoo" ]; then
        docker image tag "$DOCKER_REPO:$DOCKER_TAG.$target" "$DOCKER_REPO:$DOCKER_TAG"
    fi
done
