#!/bin/bash
set -ex

for target in base odoo enterprise; do

    # Don't build base if BUILD_TAG_BASE != true
    if [ "$target" == "base" ] && [ -z "$BUILD_TAG_BASE" ]; then
        continue
    fi

    # Don't build enterprise if version is <= 8.0
    if [ "$target" == "enterprise" ] && [[ "$DOCKER_TAG" == "7.0" || "$DOCKER_TAG" == "8.0" ]]; then
        echo "Skipping enterprise on $DOCKER_TAG"
        continue
    fi

    # Don't build enterprise if GITHUB_USER or GITHUB_TOKEN are missing.
    if [ "$target" == "enterprise" ] && [[ -z "$GITHUB_USER" || -z "$GITHUB_TOKEN" ]]; then
        echo "Can't build enterprise without GITHUB_USER and GITHUB_TOKEN"
        continue
    fi

    # Don't add a special tag for community.
    TAG="$DOCKER_REPO:$DOCKER_TAG-$target"
    if [ "$target" == "odoo" ]; then
        TAG="$DOCKER_REPO:$DOCKER_TAG"
    fi

    docker push "$TAG"
done
