#!/bin/bash
set -ex

for target in base onbuild; do
    # Don't build base if BUILD_TAG_BASE != true
    if [[ "$target" == "base" ]] && [[ -z "$BUILD_TAG_BASE" ]]; then continue; fi
    # Add a special onbuild tag
    TAG="$DOCKER_REPO:$DOCKER_TAG-$target"
    # Push it
    docker push "$TAG"
done

for target in odoo enterprise; do
    # Don't build tags that we shouldn't build
    if [[ "$target" == "odoo" ]] && [[ -z "$BUILD_TAG_ODOO" ]]; then continue; fi
    if [[ "$target" == "enterprise" ]] && [[ -z "$BUILD_TAG_ENTERPRISE" ]]; then continue; fi
    # Don't build enterprise if version is <= 8.0
    if [[ "$target" == "enterprise" ]] && [[ "$DOCKER_TAG" == "7.0" || "$DOCKER_TAG" == "8.0" ]]; then
        continue
    fi
    # Don't build enterprise if GITHUB_USER or GITHUB_TOKEN are missing.
    if [[ "$target" == "enterprise" ]] && [[ -z "$GITHUB_USER" || -z "$GITHUB_TOKEN" ]]; then
        continue
    fi
    # Odoo CE has no special tag
    # Odoo EE has -enterprise tag
    TAG="$DOCKER_REPO:$DOCKER_TAG"
    if [[ "$target" == "enterprise" ]]; then TAG="$TAG-$target"; fi
    # Push it
    docker push "$TAG"
done
